# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image_family import ImageFamily

class TestImageFamily(unittest.TestCase):
    """ImageFamily unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageFamily:
        """Test ImageFamily
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageFamily`
        """
        model = ImageFamily()
        if include_optional:
            return ImageFamily(
                ifid = 56,
                name = '',
                description = '',
                icon_url = '',
                groups = [
                    ''
                    ],
                priority = 1.337,
                disabled_reason = 56
            )
        else:
            return ImageFamily(
                ifid = 56,
                name = '',
        )
        """

    def testImageFamily(self):
        """Test ImageFamily"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
