# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.images_v1_api import ImagesV1Api


class TestImagesV1Api(unittest.TestCase):
    """ImagesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ImagesV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_image(self) -> None:
        """Test case for create_image

        """
        pass

    def test_get_images(self) -> None:
        """Test case for get_images

        """
        pass

    def test_update_image(self) -> None:
        """Test case for update_image

        """
        pass


if __name__ == '__main__':
    unittest.main()
