# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image import Image

class TestImage(unittest.TestCase):
    """Image unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Image:
        """Test Image
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Image`
        """
        model = Image()
        if include_optional:
            return Image(
                imid = 56,
                name = '',
                docker_image_url = '',
                description = '',
                description_md = '',
                public = True,
                public_description = '',
                app_type = '',
                configuration = '',
                has_tables = True,
                complexity = 56,
                tags = {
                    'key' : null
                    },
                release_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                disabled_reason = 56
            )
        else:
            return Image(
                imid = 56,
                docker_image_url = '',
                public = True,
        )
        """

    def testImage(self):
        """Test Image"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
