# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.lfs_share import LFSShare

class TestLFSShare(unittest.TestCase):
    """LFSShare unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LFSShare:
        """Test LFSShare
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LFSShare`
        """
        model = LFSShare()
        if include_optional:
            return LFSShare(
                afsid = 56,
                mount_path = '',
                name = '',
                quota_gib = 56,
                read_only = True,
                slug = '',
                subresource = ''
            )
        else:
            return LFSShare(
                afsid = 56,
                name = '',
                quota_gib = 56,
                subresource = '',
        )
        """

    def testLFSShare(self):
        """Test LFSShare"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
