# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: staging
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.instances_v1_api import InstancesV1Api


class TestInstancesV1Api(unittest.TestCase):
    """InstancesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = InstancesV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_instances(self) -> None:
        """Test case for get_instances

        """
        pass


if __name__ == '__main__':
    unittest.main()
