# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: staging
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.spaces_v1_api import SpacesV1Api


class TestSpacesV1Api(unittest.TestCase):
    """SpacesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SpacesV1Api()

    def tearDown(self) -> None:
        pass

    def test_list_space_options(self) -> None:
        """Test case for list_space_options

        """
        pass

    def test_list_spaces(self) -> None:
        """Test case for list_spaces

        """
        pass


if __name__ == '__main__':
    unittest.main()
