# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.lfsv1_api import LFSV1Api


class TestLFSV1Api(unittest.TestCase):
    """LFSV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = LFSV1Api()

    def tearDown(self) -> None:
        pass

    def test_cleanup_lfs_share(self) -> None:
        """Test case for cleanup_lfs_share

        """
        pass

    def test_list_lfs_shares(self) -> None:
        """Test case for list_lfs_shares

        """
        pass


if __name__ == '__main__':
    unittest.main()
