# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.instance_invitation_request import InstanceInvitationRequest

class TestInstanceInvitationRequest(unittest.TestCase):
    """InstanceInvitationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceInvitationRequest:
        """Test InstanceInvitationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceInvitationRequest`
        """
        model = InstanceInvitationRequest()
        if include_optional:
            return InstanceInvitationRequest(
                email = '',
                role = 'EDITOR'
            )
        else:
            return InstanceInvitationRequest(
                email = '',
                role = 'EDITOR',
        )
        """

    def testInstanceInvitationRequest(self):
        """Test InstanceInvitationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
