# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image_create import ImageCreate

class TestImageCreate(unittest.TestCase):
    """ImageCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageCreate:
        """Test ImageCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageCreate`
        """
        model = ImageCreate()
        if include_optional:
            return ImageCreate(
                name = '',
                docker_image_url = '',
                description_md = '',
                ifid = 56,
                description = '',
                public = True,
                public_description = '',
                org_slug = '',
                space_slug = '',
                app_type = '',
                configuration = {
                    'key' : null
                    },
                has_tables = True,
                complexity = 56,
                tags = {
                    'key' : null
                    }
            )
        else:
            return ImageCreate(
                name = '',
                docker_image_url = '',
                description_md = '',
                ifid = 56,
        )
        """

    def testImageCreate(self):
        """Test ImageCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
