# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: staging
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.workloads_v1_api import WorkloadsV1Api


class TestWorkloadsV1Api(unittest.TestCase):
    """WorkloadsV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkloadsV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_workload(self) -> None:
        """Test case for create_workload

        """
        pass

    def test_delete_workload_options(self) -> None:
        """Test case for delete_workload_options

        """
        pass

    def test_get_workloads(self) -> None:
        """Test case for get_workloads

        """
        pass

    def test_get_workloads_options(self) -> None:
        """Test case for get_workloads_options

        """
        pass

    def test_stop_workload(self) -> None:
        """Test case for stop_workload

        """
        pass


if __name__ == '__main__':
    unittest.main()
