# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.instance_create_request import InstanceCreateRequest

class TestInstanceCreateRequest(unittest.TestCase):
    """InstanceCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstanceCreateRequest:
        """Test InstanceCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstanceCreateRequest`
        """
        model = InstanceCreateRequest()
        if include_optional:
            return InstanceCreateRequest(
                slug = '',
                name = '',
                description = ''
            )
        else:
            return InstanceCreateRequest(
                slug = '',
                name = '',
        )
        """

    def testInstanceCreateRequest(self):
        """Test InstanceCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
