# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.sessions_v1_api import SessionsV1Api


class TestSessionsV1Api(unittest.TestCase):
    """SessionsV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_session_logs(self) -> None:
        """Test case for get_session_logs

        """
        pass

    def test_get_sessions(self) -> None:
        """Test case for get_sessions

        """
        pass


if __name__ == '__main__':
    unittest.main()
