# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image_family_response import ImageFamilyResponse

class TestImageFamilyResponse(unittest.TestCase):
    """ImageFamilyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageFamilyResponse:
        """Test ImageFamilyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageFamilyResponse`
        """
        model = ImageFamilyResponse()
        if include_optional:
            return ImageFamilyResponse(
                ifid = 56
            )
        else:
            return ImageFamilyResponse(
                ifid = 56,
        )
        """

    def testImageFamilyResponse(self):
        """Test ImageFamilyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
