# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image_update import ImageUpdate

class TestImageUpdate(unittest.TestCase):
    """ImageUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageUpdate:
        """Test ImageUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageUpdate`
        """
        model = ImageUpdate()
        if include_optional:
            return ImageUpdate(
                name = '',
                docker_image_url = '',
                description = '',
                description_md = '',
                public = True,
                public_description = '',
                app_type = '',
                configuration = {
                    'key' : null
                    },
                complexity = 56,
                tags = {
                    'key' : null
                    }
            )
        else:
            return ImageUpdate(
        )
        """

    def testImageUpdate(self):
        """Test ImageUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
