# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.group_instance_create_request import GroupInstanceCreateRequest

class TestGroupInstanceCreateRequest(unittest.TestCase):
    """GroupInstanceCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupInstanceCreateRequest:
        """Test GroupInstanceCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupInstanceCreateRequest`
        """
        model = GroupInstanceCreateRequest()
        if include_optional:
            return GroupInstanceCreateRequest(
                name = '',
                slug = '',
                description = '',
                editor_emails = [
                    ''
                    ]
            )
        else:
            return GroupInstanceCreateRequest(
                name = '',
                slug = '',
                editor_emails = [
                    ''
                    ],
        )
        """

    def testGroupInstanceCreateRequest(self):
        """Test GroupInstanceCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
