# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.image_link import ImageLink

class TestImageLink(unittest.TestCase):
    """ImageLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageLink:
        """Test ImageLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageLink`
        """
        model = ImageLink()
        if include_optional:
            return ImageLink(
                imid = 56,
                linkid = 56,
                org_slug = '',
                space_slug = '',
                priority = 56,
                space_type = 56,
                comment = ''
            )
        else:
            return ImageLink(
                imid = 56,
                linkid = 56,
        )
        """

    def testImageLink(self):
        """Test ImageLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
