# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.image_families_v1_api import ImageFamiliesV1Api


class TestImageFamiliesV1Api(unittest.TestCase):
    """ImageFamiliesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageFamiliesV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_image_family(self) -> None:
        """Test case for create_image_family

        """
        pass

    def test_get_image_families(self) -> None:
        """Test case for get_image_families

        """
        pass


if __name__ == '__main__':
    unittest.main()
