# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.api.image_links_v1_api import ImageLinksV1Api


class TestImageLinksV1Api(unittest.TestCase):
    """ImageLinksV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageLinksV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_image_links(self) -> None:
        """Test case for get_image_links

        """
        pass


if __name__ == '__main__':
    unittest.main()
