# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nuvolos_client_api.models.space_member import SpaceMember

class TestSpaceMember(unittest.TestCase):
    """SpaceMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpaceMember:
        """Test SpaceMember
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpaceMember`
        """
        model = SpaceMember()
        if include_optional:
            return SpaceMember(
                name = '',
                email = '',
                active = True,
                space_role = '',
                instance_roles = [
                    nuvolos_client_api.models.space_instance_role.SpaceInstanceRole(
                        instance_slug = '', 
                        role = '', )
                    ]
            )
        else:
            return SpaceMember(
                name = '',
                email = '',
                active = True,
                instance_roles = [
                    nuvolos_client_api.models.space_instance_role.SpaceInstanceRole(
                        instance_slug = '', 
                        role = '', )
                    ],
        )
        """

    def testSpaceMember(self):
        """Test SpaceMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
