"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import StrictBool, StrictInt, StrictStr, field_validator
from typing import List, Optional
from nuvolos_client_api.models.session import Session

from nuvolos_client_api.api_client import ApiClient, RequestSerialized
from nuvolos_client_api.api_response import ApiResponse
from nuvolos_client_api.rest import RESTResponseType


class SessionsV1Api:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_session_logs(
        self,
        session_id: StrictStr,
        container_name: StrictStr,
        max_lines: Optional[StrictInt] = None,
        from_start: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """get_session_logs

        Returns logs for the given session and container.

        :param session_id: (required)
        :type session_id: str
        :param container_name: (required)
        :type container_name: str
        :param max_lines:
        :type max_lines: int
        :param from_start:
        :type from_start: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_session_logs_serialize(
            session_id=session_id,
            container_name=container_name,
            max_lines=max_lines,
            from_start=from_start,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_session_logs_with_http_info(
        self,
        session_id: StrictStr,
        container_name: StrictStr,
        max_lines: Optional[StrictInt] = None,
        from_start: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """get_session_logs

        Returns logs for the given session and container.

        :param session_id: (required)
        :type session_id: str
        :param container_name: (required)
        :type container_name: str
        :param max_lines:
        :type max_lines: int
        :param from_start:
        :type from_start: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_session_logs_serialize(
            session_id=session_id,
            container_name=container_name,
            max_lines=max_lines,
            from_start=from_start,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_session_logs_without_preload_content(
        self,
        session_id: StrictStr,
        container_name: StrictStr,
        max_lines: Optional[StrictInt] = None,
        from_start: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get_session_logs

        Returns logs for the given session and container.

        :param session_id: (required)
        :type session_id: str
        :param container_name: (required)
        :type container_name: str
        :param max_lines:
        :type max_lines: int
        :param from_start:
        :type from_start: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_session_logs_serialize(
            session_id=session_id,
            container_name=container_name,
            max_lines=max_lines,
            from_start=from_start,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_session_logs_serialize(
        self,
        session_id,
        container_name,
        max_lines,
        from_start,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if session_id is not None:
            _path_params['session_id'] = session_id
        if container_name is not None:
            _path_params['container_name'] = container_name
        # process the query parameters
        if max_lines is not None:
            
            _query_params.append(('max_lines', max_lines))
            
        if from_start is not None:
            if isinstance(from_start, datetime):
                _query_params.append(
                    (
                        'from_start',
                        from_start.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('from_start', from_start))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    '*/*'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/sessions/v1/{session_id}/container/{container_name}/logs',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_sessions(
        self,
        org_slug: StrictStr,
        space_slug: StrictStr,
        instance_slug: StrictStr,
        app_slug: StrictStr,
        page: Optional[StrictInt] = None,
        per_page: Optional[StrictInt] = None,
        metadata: Optional[StrictBool] = None,
        order_by: Optional[StrictStr] = None,
        session_id: Optional[StrictStr] = None,
        sort: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[Session]:
        """get_sessions

        Returns sessions for the given Nuvolos application.

        :param org_slug: (required)
        :type org_slug: str
        :param space_slug: (required)
        :type space_slug: str
        :param instance_slug: (required)
        :type instance_slug: str
        :param app_slug: (required)
        :type app_slug: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param metadata:
        :type metadata: bool
        :param order_by:
        :type order_by: str
        :param session_id:
        :type session_id: str
        :param sort:
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sessions_serialize(
            org_slug=org_slug,
            space_slug=space_slug,
            instance_slug=instance_slug,
            app_slug=app_slug,
            page=page,
            per_page=per_page,
            metadata=metadata,
            order_by=order_by,
            session_id=session_id,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[Session]",
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_sessions_with_http_info(
        self,
        org_slug: StrictStr,
        space_slug: StrictStr,
        instance_slug: StrictStr,
        app_slug: StrictStr,
        page: Optional[StrictInt] = None,
        per_page: Optional[StrictInt] = None,
        metadata: Optional[StrictBool] = None,
        order_by: Optional[StrictStr] = None,
        session_id: Optional[StrictStr] = None,
        sort: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[Session]]:
        """get_sessions

        Returns sessions for the given Nuvolos application.

        :param org_slug: (required)
        :type org_slug: str
        :param space_slug: (required)
        :type space_slug: str
        :param instance_slug: (required)
        :type instance_slug: str
        :param app_slug: (required)
        :type app_slug: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param metadata:
        :type metadata: bool
        :param order_by:
        :type order_by: str
        :param session_id:
        :type session_id: str
        :param sort:
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sessions_serialize(
            org_slug=org_slug,
            space_slug=space_slug,
            instance_slug=instance_slug,
            app_slug=app_slug,
            page=page,
            per_page=per_page,
            metadata=metadata,
            order_by=order_by,
            session_id=session_id,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[Session]",
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_sessions_without_preload_content(
        self,
        org_slug: StrictStr,
        space_slug: StrictStr,
        instance_slug: StrictStr,
        app_slug: StrictStr,
        page: Optional[StrictInt] = None,
        per_page: Optional[StrictInt] = None,
        metadata: Optional[StrictBool] = None,
        order_by: Optional[StrictStr] = None,
        session_id: Optional[StrictStr] = None,
        sort: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get_sessions

        Returns sessions for the given Nuvolos application.

        :param org_slug: (required)
        :type org_slug: str
        :param space_slug: (required)
        :type space_slug: str
        :param instance_slug: (required)
        :type instance_slug: str
        :param app_slug: (required)
        :type app_slug: str
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param metadata:
        :type metadata: bool
        :param order_by:
        :type order_by: str
        :param session_id:
        :type session_id: str
        :param sort:
        :type sort: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sessions_serialize(
            org_slug=org_slug,
            space_slug=space_slug,
            instance_slug=instance_slug,
            app_slug=app_slug,
            page=page,
            per_page=per_page,
            metadata=metadata,
            order_by=order_by,
            session_id=session_id,
            sort=sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[Session]",
            '400': "ClientApiError",
            '401': None,
            '403': "ClientApiError",
            '404': "ClientApiError",
            '409': "ClientApiError",
            '410': "ClientApiError",
            '500': "ClientApiError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_sessions_serialize(
        self,
        org_slug,
        space_slug,
        instance_slug,
        app_slug,
        page,
        per_page,
        metadata,
        order_by,
        session_id,
        sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if org_slug is not None:
            _path_params['org_slug'] = org_slug
        if space_slug is not None:
            _path_params['space_slug'] = space_slug
        if instance_slug is not None:
            _path_params['instance_slug'] = instance_slug
        if app_slug is not None:
            _path_params['app_slug'] = app_slug
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if metadata is not None:
            
            _query_params.append(('metadata', metadata))
            
        if order_by is not None:
            
            _query_params.append(('order_by', order_by))
            
        if session_id is not None:
            
            _query_params.append(('session_id', session_id))
            
        if sort is not None:
            
            _query_params.append(('sort', sort))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    '*/*'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKeyAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/sessions/v1/org/{org_slug}/space/{space_slug}/instance/{instance_slug}/app/{app_slug}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


