# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FilePublic(BaseModel):
    """
    FilePublic
    """ # noqa: E501
    fid: StrictStr
    short_id: StrictStr
    creation_timestamp: Optional[StrictStr] = None
    last_modified_timestamp: Optional[StrictStr] = None
    type: StrictStr
    size: Optional[StrictInt] = None
    area: StrictStr
    local_path: StrictStr
    history: Optional[Dict[str, Any]] = None
    is_video: Optional[StrictBool] = None
    status: Optional[Dict[str, Any]] = None
    collision_info: Optional[Dict[str, Any]] = None
    snapshot_slug: Optional[StrictStr] = None
    os_path: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["fid", "short_id", "creation_timestamp", "last_modified_timestamp", "type", "size", "area", "local_path", "history", "is_video", "status", "collision_info", "snapshot_slug", "os_path"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FilePublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FilePublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fid": obj.get("fid"),
            "short_id": obj.get("short_id"),
            "creation_timestamp": obj.get("creation_timestamp"),
            "last_modified_timestamp": obj.get("last_modified_timestamp"),
            "type": obj.get("type"),
            "size": obj.get("size"),
            "area": obj.get("area"),
            "local_path": obj.get("local_path"),
            "history": obj.get("history"),
            "is_video": obj.get("is_video"),
            "status": obj.get("status"),
            "collision_info": obj.get("collision_info"),
            "snapshot_slug": obj.get("snapshot_slug"),
            "os_path": obj.get("os_path")
        })
        return _obj


