# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImageUpdate(BaseModel):
    """
    ImageUpdate
    """ # noqa: E501
    name: Optional[StrictStr] = None
    docker_image_url: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    description_md: Optional[StrictStr] = None
    public: Optional[StrictBool] = None
    public_description: Optional[StrictStr] = None
    app_type: Optional[StrictStr] = None
    configuration: Optional[Dict[str, Any]] = None
    complexity: Optional[StrictInt] = None
    tags: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["name", "docker_image_url", "description", "description_md", "public", "public_description", "app_type", "configuration", "complexity", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if description_md (nullable) is None
        # and model_fields_set contains the field
        if self.description_md is None and "description_md" in self.model_fields_set:
            _dict['description_md'] = None

        # set to None if public_description (nullable) is None
        # and model_fields_set contains the field
        if self.public_description is None and "public_description" in self.model_fields_set:
            _dict['public_description'] = None

        # set to None if app_type (nullable) is None
        # and model_fields_set contains the field
        if self.app_type is None and "app_type" in self.model_fields_set:
            _dict['app_type'] = None

        # set to None if configuration (nullable) is None
        # and model_fields_set contains the field
        if self.configuration is None and "configuration" in self.model_fields_set:
            _dict['configuration'] = None

        # set to None if complexity (nullable) is None
        # and model_fields_set contains the field
        if self.complexity is None and "complexity" in self.model_fields_set:
            _dict['complexity'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "docker_image_url": obj.get("docker_image_url"),
            "description": obj.get("description"),
            "description_md": obj.get("description_md"),
            "public": obj.get("public"),
            "public_description": obj.get("public_description"),
            "app_type": obj.get("app_type"),
            "configuration": obj.get("configuration"),
            "complexity": obj.get("complexity"),
            "tags": obj.get("tags")
        })
        return _obj


