# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Image(BaseModel):
    """
    Image
    """ # noqa: E501
    imid: StrictInt
    name: Optional[StrictStr] = None
    docker_image_url: StrictStr
    description: Optional[StrictStr] = None
    description_md: Optional[StrictStr] = None
    public: StrictBool
    public_description: Optional[StrictStr] = None
    app_type: Optional[StrictStr] = None
    configuration: Optional[StrictStr] = None
    has_tables: Optional[StrictBool] = None
    complexity: Optional[StrictInt] = None
    tags: Optional[Dict[str, Any]] = None
    release_date: Optional[date] = None
    disabled_reason: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["imid", "name", "docker_image_url", "description", "description_md", "public", "public_description", "app_type", "configuration", "has_tables", "complexity", "tags", "release_date", "disabled_reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Image from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if description_md (nullable) is None
        # and model_fields_set contains the field
        if self.description_md is None and "description_md" in self.model_fields_set:
            _dict['description_md'] = None

        # set to None if public_description (nullable) is None
        # and model_fields_set contains the field
        if self.public_description is None and "public_description" in self.model_fields_set:
            _dict['public_description'] = None

        # set to None if app_type (nullable) is None
        # and model_fields_set contains the field
        if self.app_type is None and "app_type" in self.model_fields_set:
            _dict['app_type'] = None

        # set to None if configuration (nullable) is None
        # and model_fields_set contains the field
        if self.configuration is None and "configuration" in self.model_fields_set:
            _dict['configuration'] = None

        # set to None if has_tables (nullable) is None
        # and model_fields_set contains the field
        if self.has_tables is None and "has_tables" in self.model_fields_set:
            _dict['has_tables'] = None

        # set to None if complexity (nullable) is None
        # and model_fields_set contains the field
        if self.complexity is None and "complexity" in self.model_fields_set:
            _dict['complexity'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if release_date (nullable) is None
        # and model_fields_set contains the field
        if self.release_date is None and "release_date" in self.model_fields_set:
            _dict['release_date'] = None

        # set to None if disabled_reason (nullable) is None
        # and model_fields_set contains the field
        if self.disabled_reason is None and "disabled_reason" in self.model_fields_set:
            _dict['disabled_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Image from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "imid": obj.get("imid"),
            "name": obj.get("name"),
            "docker_image_url": obj.get("docker_image_url"),
            "description": obj.get("description"),
            "description_md": obj.get("description_md"),
            "public": obj.get("public"),
            "public_description": obj.get("public_description"),
            "app_type": obj.get("app_type"),
            "configuration": obj.get("configuration"),
            "has_tables": obj.get("has_tables"),
            "complexity": obj.get("complexity"),
            "tags": obj.get("tags"),
            "release_date": obj.get("release_date"),
            "disabled_reason": obj.get("disabled_reason")
        })
        return _obj


