# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ImageLink(BaseModel):
    """
    ImageLink
    """ # noqa: E501
    imid: StrictInt
    linkid: StrictInt
    org_slug: Optional[StrictStr] = None
    space_slug: Optional[StrictStr] = None
    priority: Optional[StrictInt] = None
    space_type: Optional[StrictInt] = None
    comment: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["imid", "linkid", "org_slug", "space_slug", "priority", "space_type", "comment"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ImageLink from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if org_slug (nullable) is None
        # and model_fields_set contains the field
        if self.org_slug is None and "org_slug" in self.model_fields_set:
            _dict['org_slug'] = None

        # set to None if space_slug (nullable) is None
        # and model_fields_set contains the field
        if self.space_slug is None and "space_slug" in self.model_fields_set:
            _dict['space_slug'] = None

        # set to None if priority (nullable) is None
        # and model_fields_set contains the field
        if self.priority is None and "priority" in self.model_fields_set:
            _dict['priority'] = None

        # set to None if space_type (nullable) is None
        # and model_fields_set contains the field
        if self.space_type is None and "space_type" in self.model_fields_set:
            _dict['space_type'] = None

        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ImageLink from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "imid": obj.get("imid"),
            "linkid": obj.get("linkid"),
            "org_slug": obj.get("org_slug"),
            "space_slug": obj.get("space_slug"),
            "priority": obj.get("priority"),
            "space_type": obj.get("space_type"),
            "comment": obj.get("comment")
        })
        return _obj


