# coding: utf-8

"""
    Nuvolos

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: prod
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nuvolos_client_api.models.space_instance_role import SpaceInstanceRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SpaceMember(BaseModel):
    """
    SpaceMember
    """ # noqa: E501
    name: StrictStr
    email: StrictStr
    active: StrictBool
    space_role: Optional[StrictStr] = None
    instance_roles: List[SpaceInstanceRole]
    __properties: ClassVar[List[str]] = ["name", "email", "active", "space_role", "instance_roles"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpaceMember from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instance_roles (list)
        _items = []
        if self.instance_roles:
            for _item_instance_roles in self.instance_roles:
                if _item_instance_roles:
                    _items.append(_item_instance_roles.to_dict())
            _dict['instance_roles'] = _items
        # set to None if space_role (nullable) is None
        # and model_fields_set contains the field
        if self.space_role is None and "space_role" in self.model_fields_set:
            _dict['space_role'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpaceMember from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "email": obj.get("email"),
            "active": obj.get("active"),
            "space_role": obj.get("space_role"),
            "instance_roles": [SpaceInstanceRole.from_dict(_item) for _item in obj["instance_roles"]] if obj.get("instance_roles") is not None else None
        })
        return _obj


