name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Publish Python package to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install python
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        python-version: 3.8

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="/home/runner/.local/bin:$PATH"

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}